@extends('layouts.app')

@section('title', $post->meta_title ?: $post->title . ' - Aquahub.pro')
@section('meta_description', $post->meta_description ?: $post->excerpt)
@section('meta_image', $post->featured_image ? asset('storage/' . $post->featured_image) : asset('images/og-default.jpg'))

@section('content')
<div style="background: white; padding: 4rem 0 2rem;">
    <div class="container container-sm" style="max-width: 800px;">
        <div style="margin-bottom: 2rem;">
            <a href="/category/{{ $post->category->slug }}" style="color: var(--primary); text-transform: uppercase; font-size: 0.75rem; font-weight: 700;">{{ $post->category->name }}</a>
            <h1 style="font-size: 3rem; margin: 1rem 0; line-height: 1.1;">{{ $post->title }}</h1>
            <div style="display: flex; align-items: center; gap: 1rem; color: #64748b; font-size: 0.875rem;">
                <div style="display: flex; align-items: center; gap: 0.5rem;">
                    <div style="width: 32px; height: 32px; background: #e2e8f0; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 800; font-size: 0.75rem; color: #0284c7;">A</div>
                    <span>{{ $post->author->name }}</span>
                </div>
                <span>•</span>
                <span>Last updated on {{ $post->updated_at->format('M d, Y') }}</span>
            </div>
        </div>
    </div>
</div>

<div class="container" style="display: grid; grid-template-columns: 1fr 300px; gap: 4rem; padding: 0 1.5rem 6rem; position: relative; max-width: 1200px;">
    <!-- Main Content -->
    <article style="max-width: 800px; min-width: 0;">
        @if($post->featured_image)
            <img src="{{ asset('storage/' . $post->featured_image) }}" alt="{{ $post->title }}" style="width: 100%; border-radius: 12px; margin-bottom: 3rem; box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1);">
        @endif

        <div id="toc-container" style="background: #f8fafc; padding: 1.5rem; border-radius: 8px; border: 1px solid #e2e8f0; margin-bottom: 3rem;">
            <h4 style="margin-bottom: 1rem; font-size: 1.125rem;">Table of Contents</h4>
            <ul id="toc-list" style="list-style: none; display: flex; flex-direction: column; gap: 0.5rem; font-size: 0.9375rem;">
                <!-- Generated by JS -->
            </ul>
        </div>

        <div class="prose" style="line-height: 1.8; font-size: 1.125rem; color: #334155;">
            {!! $post->renderContent() !!}
        </div>

        @if($post->faqs->count() > 0)
        <div id="faq" style="margin-top: 5rem; padding-top: 3rem; border-top: 1px solid #e2e8f0;">
            <h2 style="margin-bottom: 2rem;">Frequently Asked Questions</h2>
            <div style="display: flex; flex-direction: column; gap: 2rem;">
                @foreach($post->faqs as $faq)
                <div style="background: #f8fafc; padding: 1.5rem; border-radius: 8px;">
                    <h3 style="font-size: 1.25rem; margin-bottom: 0.75rem;">{{ $faq->question }}</h3>
                    <p style="color: #475569;">{{ $faq->answer }}</p>
                </div>
                @endforeach
            </div>
        </div>
        @endif

        <div style="margin-top: 5rem; padding: 2rem; border-radius: 12px; background: #0f172a; color: white;">
            <h3 style="color: white; margin-bottom: 1rem;">Share this guide</h3>
            <div style="display: flex; gap: 1rem;">
                <a href="https://twitter.com/intent/tweet?text={{ urlencode($post->title) }}&url={{ url()->current() }}" class="btn" style="background: #1da1f2; color: white; flex: 1; justify-content: center; font-size: 0.8125rem;">Twitter</a>
                <a href="https://www.facebook.com/sharer/sharer.php?u={{ url()->current() }}" class="btn" style="background: #1877f2; color: white; flex: 1; justify-content: center; font-size: 0.8125rem;">Facebook</a>
            </div>
        </div>
    </article>

    <!-- Sidebar -->
    <aside style="height: fit-content; position: sticky; top: 100px;">
        <div style="background: #f0f9ff; padding: 1.5rem; border-radius: 12px; border: 1px solid #bae6fd; margin-bottom: 2rem;">
            <h4 style="color: #0369a1; margin-bottom: 1rem;">Top Rated Choice</h4>
            <div style="background: white; border-radius: 8px; padding: 1rem; text-align: center; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.05);">
                <div style="width: 120px; height: 120px; background: #f8fafc; margin: 0 auto 1.5rem; display: flex; align-items: center; justify-content: center; font-size: 3rem;">🛍️</div>
                <h5 style="margin-bottom: 0.5rem; font-size: 0.875rem;">Fluval Flex Marine Kit</h5>
                <p style="font-size: 0.75rem; color: #64748b; margin-bottom: 1.5rem;">Perfect for saltwater beginners.</p>
                <a href="#" class="btn btn-primary" style="width: 100%; justify-content: center; font-size: 0.875rem;">Check Price on Amazon</a>
                <p style="font-size: 0.625rem; color: #94a3b8; margin-top: 1rem;">As an Amazon Associate, we earn from qualifying purchases.</p>
            </div>
        </div>

        <div style="display: flex; flex-direction: column; gap: 1.5rem;">
            <h4 style="font-size: 0.875rem; text-transform: uppercase; color: #94a3b8; letter-spacing: 0.05em;">Related Posts</h4>
            @foreach($related_posts as $related)
            <a href="/blog/{{ $related->slug }}" style="display: flex; gap: 1rem; text-decoration: none;">
                <div style="width: 60px; height: 60px; background: #e2e8f0; border-radius: 4px; overflow: hidden; flex-shrink: 0;">
                    @if($related->featured_image)
                        <img src="{{ asset('storage/' . $related->featured_image) }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                    @endif
                </div>
                <div>
                    <h5 style="margin-bottom: 0.25rem; font-size: 0.875rem; line-height: 1.3; color: #0f172a;">{{ $related->title }}</h5>
                    <span style="font-size: 0.75rem; color: #64748b;">{{ $related->published_at?->format('M d, Y') ?? 'N/A' }}</span>
                </div>
            </a>
            @endforeach
        </div>
    </aside>
</div>

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": "{{ $post->title }}",
  "image": ["{{ $post->featured_image ? asset('storage/' . $post->featured_image) : asset('images/og-default.jpg') }}"],
  "datePublished": "{{ $post->published_at?->toIso8601String() }}",
  "dateModified": "{{ $post->updated_at?->toIso8601String() }}",
  "author": [{
      "@type": "Person",
      "name": "{{ $post->author->name }}",
      "url": "{{ url()->current() }}"
    }]
}
</script>

@if($post->faqs->count() > 0)
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    @foreach($post->faqs as $faq)
    {
      "@type": "Question",
      "name": "{{ $faq->question }}",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "{{ $faq->answer }}"
      }
    }{{ !$loop->last ? ',' : '' }}
    @endforeach
  ]
}
</script>
@endif

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const tocList = document.getElementById('toc-list');
        const headings = document.querySelectorAll('article h2, article h3');
        
        if (headings.length === 0) {
            document.getElementById('toc-container').style.display = 'none';
            return;
        }

        headings.forEach((heading, index) => {
            const id = 'heading-' + index;
            heading.setAttribute('id', id);
            
            const li = document.createElement('li');
            const a = document.createElement('a');
            a.href = '#' + id;
            a.textContent = heading.textContent;
            a.style.color = 'inherit';
            a.style.textDecoration = 'none';
            
            if (heading.tagName === 'H3') {
                li.style.paddingLeft = '1rem';
                li.style.color = '#64748b';
                li.style.fontSize = '0.8125rem';
            } else {
                li.style.fontWeight = '600';
            }

            li.appendChild(a);
            tocList.appendChild(li);
        });
    });
</script>
@endpush
@endsection
